### PR TITLE
replace “minifier” with “clean-css”

### PR DESCRIPTION
**Pull request by marcobiedermann**
I've replaces [`minifier`](https://github.com/fizker/minifier) with [`clean-css`](https://github.com/jakubpawlowicz/clean-css) which saves some extra bytes. It is also way more maintained and used.

```
before: 6195 bytes
after : 6041 bytes
diff  :  154 bytes
```

Not much bit every byte counts :)

### CODE REVIEW

**Comment by ghosh** [comment]
@marcobiedermann Thanks! This is fantastic. Merged,

**Comment by marcobiedermann** [comment]
@ghosh You are very welcome :)

I've checked [`package.json`](https://github.com/ghosh/microtip/blob/master/package.json) after merge but it does not look right. Are you sure you merged me PR into master?

**Comment by ghosh** [comment]
@marcobiedermann Hi, yes I did merge it at one point - see 553ce6b

However, there was an issue where the minified code was breaking some of the styles of the tooltips. At that point, I didn't have time to investigate, hence reverted back to older minifier. I do hope to switch it out with `clean-css` at som point though.

**Comment by marcobiedermann** [comment]
Alright, I'll check the ouput again

**Pull request merged**
